Add tables endpoint
tastyigniter/ti-ext-api pull request #29
Opened 2020-12-28 18:14 UTC by ryanmitchell

Endpoint + docs in new API format.

2020-12-29 13:48 UTC, sampoyigi commented
Adding a new endpoint is amazingly clean and simple 🤯. Love it!!!

2020-12-29 13:50 UTC, ryanmitchell commented
Most of the work is writing the docs :)

2020-12-29 13:54 UTC, sampoyigi commented
Lol, we could go extreme and integrate something like Swagger to generate the docs 🤷‍♂️

2020-12-29 13:56 UTC, ryanmitchell commented
Nah its good - we've done all the main ones so its just filling gaps from now.
I'll work on the new doc responses and rules this week.

2020-12-29 14:02 UTC, sampoyigi commented
Hehehe, I wasn't serious about that. There's only so much we can do 😄

2020-12-31 19:31 UTC, sampoyigi requested changes
Last one ;)

2020-12-31 19:31 UTC, sampoyigi commented on Extension.php
> +                    'index:users', 'show:users',
All actions should be limited to just the admin.

2020-12-31 22:19 UTC, ryanmitchell commented on Extension.php
> +                    'index:users', 'show:users',
Done :)

2021-01-04 13:45 UTC, sampoyigi approved these changes

2021-01-04 13:45 UTC, merged