Category docs
tastyigniter/ti-ext-api pull request #30
Opened 2020-12-30 12:08 UTC by ryanmitchell

Docs for JSONApi/Dingo branch

2020-12-30 15:17 UTC, sampoyigi requested changes

2020-12-30 15:17 UTC, sampoyigi commented on docs/categories.md
> +      "count": 8,
should be 1 ;)

2020-12-30 15:17 UTC, sampoyigi commented on docs/categories.md
> +The endpoint responses are formatted according to the [JSONApi specification](https://jsonapi.org).
Its written as `JSON:API`

2020-12-30 15:41 UTC, ryanmitchell commented
Thanks - I'll roll it out to the others tonight/tomorrow

2021-01-04 20:20 UTC, sampoyigi approved these changes

2021-01-04 20:20 UTC, merged