Currency and address on orders
tastyigniter/ti-ext-api pull request #33
Opened 2021-01-13 08:26 UTC by ryanmitchell

Fix bug when there was no address (collection)
Unserialize menu options
Add currency helpers so the API client doesnt need to do this (they shouldnt)

2021-01-14 16:15 UTC, sampoyigi requested changes

2021-01-14 16:15 UTC, sampoyigi commented on apiresources/transformers/OrderTransformer.php
> +            'order_total_as_currency' => currency_format($order->order_total),
Hmm, I don't like the idea of responding with formatted data, we should definitely leave that to frontend libraries... 

Also for consistency's sake, we can either add a new item `order_menu_options` to the array or add a new method `getOrderMenusWithOptions` or improve `getOrderMenus` to return `getOrderMenuOptions` merged into `getOrderMenus `... We should be using the result from `getOrderMenuOptions` instead of `$menu->option_values` as `option_values` is sort of deprecated.

2021-01-14 16:59 UTC, ryanmitchell commented
Ok. It just means every integration needs to recreate the currency logic - which seems a bit redundant when we can add it quite simply to the response. 

I’ll look into a better way to do order menus options tomorrow. 




> On 14 Jan 2021, at 16:16, Sam Poyigi <notifications@github.com> wrote:
> 
> ﻿
> @sampoyigi requested changes on this pull request.
> 
> In apiresources/transformers/OrderTransformer.php:
> 
> > @@ -21,13 +21,23 @@ class OrderTransformer extends TransformerAbstract
>      public function transform(Orders_model $order)
>      {
>          return array_merge($order->toArray(), [
> -            'order_totals' => $order->getOrderTotals(),
> -            'order_menus' => $order->getOrderMenus(),
> +            'order_total_as_currency' => currency_format($order->order_total),
> Hmm, I don't like the idea of responding with formatted data, we should definitely leave that to frontend libraries...
> 
> Also for consistency's sake, we can either add a new item order_menu_options to the array or add a new method getOrderMenusWithOptions or improve getOrderMenus to return getOrderMenuOptions merged into getOrderMenus ... We should be using the result from getOrderMenuOptions instead of $menu->option_values as option_values is sort of deprecated.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-14 17:37 UTC, sampoyigi commented
Might be redundant in some cases but I've not come across an API that returns price with the currency symbol.

One thing I've seen which we can do for price is format them to something like `{"currency": "GBP", "value": "amount_in_cents_or_float"}`

2021-01-14 17:59 UTC, ryanmitchell commented
Yep that might work. 

Just thinking of the formatting options we give like thousand separator and decimal separator and decimal count - would be helpful to not have to replicate it all client side. Maybe we just need to provide a settings end point to give visibility to those?



> On 14 Jan 2021, at 17:37, Sam Poyigi <notifications@github.com> wrote:
> 
> ﻿
> Might be redundant in some cases but I've not come across an API that returns price with the currency symbol.
> 
> One thing I've seen which we can do for price is format them to something like {"currency": "GBP", "value": "amount_in_cents_or_float"}
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-14 18:14 UTC, sampoyigi commented
Yep, that's more like it, return the raw floats or a price format and add a new endpoint to pull currencies then let the frontend handle the formatting.

If we choose the price format (`{"currency": "GBP", "value": "amount_in_cents_or_float"}`), we must do same for other price values.

2021-01-14 18:49 UTC, ryanmitchell commented
Yep so we would need a new end point for admin\system\settings so that the default currency can be retrieved.
And then another for admin\system\currencies so that the formatting settings can be retrieved.

I’ve just given myself a lot of work… :)



> On 14 Jan 2021, at 18:15, Sam Poyigi <notifications@github.com> wrote:
> 
> 
> Yep, that's more like it, return the raw floats or a price format and add a new endpoint to pull currencies then let the frontend handle the formatting.
> 
> If we choose the price format ({"currency": "GBP", "value": "amount_in_cents_or_float"}), we must do same for other price values.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/tastyigniter/ti-ext-api/pull/33#issuecomment-760373588>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAAMVO74GMK7V7SX5DY7VT3SZ4YCRANCNFSM4WANUHTQ>.
>

2021-01-14 19:41 UTC, ryanmitchell commented
The other option that occurred to me would be a relation between orders / menu items and currency. Would allow for the possibility of multiple currencies in the future?

2021-01-14 22:56 UTC, sampoyigi commented
> The other option that occurred to me would be a relation between orders / menu items and currency. Would allow for the possibility of multiple currencies in the future?

Not sure how this would work.

If we're going to add the currencies endpoint then we should change the responses to save us from adding a system/settings endpoint since we'll know which currency to format the price from the response. ie. `{currency: GBP, value: 38.293}`

With my recent changes to the API PR, we can register a single `list` action for the currencies endpoint.

2021-01-15 07:34 UTC, ryanmitchell commented on apiresources/transformers/OrderTransformer.php
> +            'order_total_as_currency' => currency_format($order->order_total),
Ok, I've opened up a PR for this in core

2021-01-15 07:36 UTC, ryanmitchell commented
Ok, I've pushed a change to the orders transformer that does this - let me know what you think. It may be better to just add a currency_code key to the main orders response, and then any values can be treated as that currency?

Will open a separate PR for the currencies end point

2021-01-19 11:29 UTC, sampoyigi requested changes

2021-01-19 11:29 UTC, sampoyigi commented on apiresources/transformers/OrderTransformer.php
> +
Add a formatToJson method to the Currency service then a helper method `currency_json`...

2021-01-19 11:34 UTC, ryanmitchell commented on apiresources/transformers/LocationTransformer.php
> +        ]);
Done

2021-01-19 11:34 UTC, ryanmitchell commented on apiresources/transformers/OrderTransformer.php
> +
What do you want returned in the JSON - at the moment its just the code

2021-01-19 16:00 UTC, sampoyigi commented on apiresources/transformers/OrderTransformer.php
> +
the toJson method would return an array 
```
[
  'currency' => 'GBP',
  'amount' => ''
]
```

2021-01-19 16:31 UTC, ryanmitchell commented
Thanks - I understand now what you mean.

> On 19 Jan 2021, at 16:01, Sam Poyigi <notifications@github.com> wrote:
> 
> ﻿
> @sampoyigi commented on this pull request.
> 
> In apiresources/transformers/OrderTransformer.php:
> 
> > +        if (!$this->currency_code)
> +            $this->currency_code = app('currency')->getDefault()->currency_code;
> +
> +        $currency_code = $this->currency_code;
> +
> the toJson method would return an array
> 
> [
>   'currency' => 'GBP',
>   'amount' => ''
> ]
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-19 17:11 UTC, ryanmitchell commented on apiresources/transformers/OrderTransformer.php
> +
Done, and PR in flame opened

2021-01-21 22:39 UTC, sampoyigi commented
Added changes to mutate the order_total attribute and format other prices on the response, we should do the same for other endpoints with monetary values as well as update the docs.

2021-01-22 10:10 UTC, ryanmitchell commented
I've updated menus and menu option values, however I've noticed a potential issue.
The transformers only affect values in the "included" array - run a check on the menus with `?include=menu_options.menu_option_values` - the main `data` key hasn't got the prices with currency, but the included does...

2021-01-22 12:31 UTC, sampoyigi commented
Thank you!

Looking at the JSON:API specs, relationships are not included in the attributes array, they are only available in the included array, so we need a way to exclude relationships from the returned `toArray` result. Maybe there's a Laravel way of doing this? Do you want to have a go?

2021-01-22 13:40 UTC, ryanmitchell commented
So you can use makeHidden() e.g. on menustransformer

```
    public function transform(Menus_model $menuItem)
    {
        $keysToRemove = array_keys($menuItem->getRelations());
        return array_merge($menuItem->makeHidden($keysToRemove)->toArray(), [
            'menu_price' => currency_json($menuItem->menu_price),
        ]);
    }
```

If youre happy with this approach we should abstract out and have our own transformer that does this automatically

2021-01-25 18:05 UTC, sampoyigi commented
Nice one, first time i'm seeing the `makeHidden` method. Since we have a _repository_ layer we should make the changes there.. Somewhere within the model extend callback in the `AbstractRepository::createModel` method

2021-01-25 18:58 UTC, ryanmitchell commented
Yeah i stumbled across it... useful for this!
Added to abstract repository

2021-01-25 19:22 UTC, sampoyigi commented on classes/AbstractRepository.php
> +
At the stage, relations are not yet loaded so `getRelations` will return an empty array, we can use `getRelationDefinitions` to get the defined relation names.

2021-01-25 19:29 UTC, sampoyigi commented
I think the currency format thing I suggested is a bit too much. Never will an endpoint return monetary values with different currencies, so it makes sense to have a single currency item on the response array. I'll revert the `currency_json` helper and you revert the changes here to add a single `'currency' => 'GBP'` to endpoints where its needed. Pardon the back and forth :)

2021-01-25 20:07 UTC, ryanmitchell commented
Done :)

2021-01-25 21:00 UTC, sampoyigi commented on classes/AbstractRepository.php
> +            if ($relationKeys = collect($model->getRelationDefinitions())->collapse()->keys())
Nice... you've really got this collection thing on lock! 👍

2021-01-25 21:01 UTC, sampoyigi commented on apiresources/repositories/OrderRepository.php
> +    }
You missed this ;)

2021-01-25 21:58 UTC, sampoyigi approved these changes

2021-01-25 21:59 UTC, merged

2021-01-25 21:59 UTC, sampoyigi commented
Thank you!